## Numpy array operation 

import numpy as np

In [5]:
import numpy as np

basic slicing

In [6]:
arr=np.array([2,4,6,8,10,1,3,5,7,9])
print(arr[3:7]) ## basic slicing
print(arr[1:8:2])  # Slicing with step
print(arr[-3]) ##negetive indexing in py

[ 8 10  1  3]
[4 8 1 5]
5


In [7]:
arr_2D=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]
                 ])
print("position (2,3): ",arr_2D[1,2])
print("whole row: ",arr_2D[2])
print("entire column: ",arr_2D[:,1])

position (2,3):  6
whole row:  [7 8 9]
entire column:  [2 5 8]


## sorting

In [8]:
uunsorted=np.array([3,1,2,4,5,7,6])
sorted=np.sort(uunsorted)
print(sorted)

[1 2 3 4 5 6 7]


In [9]:
arr_2D_unsorted=np.array([[2,1],
                          [6,5],
                          [4,3]
                          ])
print(np.sort(arr_2D_unsorted,axis=0)) ## top to bottom

print(np.sort(arr_2D_unsorted,axis=1)) ##left to right

[[2 1]
 [4 3]
 [6 5]]
[[1 2]
 [5 6]
 [3 4]]


## Filtering

In [10]:
number=np.array([1,2,3,4,5,6,7,8])
even_numbers=number[number%2==0]
print(even_numbers)

[2 4 6 8]


In [11]:
## filter with mask
mask=number>5
print("number greater than 5: " ,number[mask])


number greater than 5:  [6 7 8]


In [12]:
condition_array=np.array(number>5) ## return bool result for the condition
print(condition_array)

[False False False False False  True  True  True]


In [13]:
np_2_array=np.where(number>5,number*4,number)
print(np_2_array)

#syntx like:

# if(number>5){
#     number*4
# }else{
#     number
# }


[ 1  2  3  4  5 24 28 32]


In [14]:
np_3_array=np.where(number>5,"true","false")
print(np_3_array)

#syntx like:

# if(number>5){
#     true
# }else{
#    false
# }

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true']


## adding and removing data

In [21]:
#merging two arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=arr1+arr2
print(combined)

concat=np.concatenate((arr1,arr2))
print(concat)

[5 7 9]
[1 2 3 4 5 6]


## aray compatibility

In [23]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3,4])
print("compatibilty: ",arr1.shape==arr2.shape)

compatibilty:  False


In [31]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

with_new_row=np.vstack((original,new_row)) #add new row
print(with_new_row)


new_col=np.array([[7],[8],[3]])
with_new_col=np.hstack((with_new_row,new_col)) #add new column
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]
 [5 6 3]]


In [ ]:
# deleting

arr=np.array([1,2,3,4])
deleted=np.delete(arr,2)
print(deleted) #array after deletion

[1 2 4]
