## numoy array and basics 
learn abot numpy

In [1]:
import numpy as np



In [2]:
## creating  array from arrray listy

In [6]:
array_1d=np.array([1,2,3,4,5])
print("1D array: ",array_1d)


1D array:  [1 2 3 4 5]


In [9]:
array_2d=np.array([[1,2,3],[4,5,6]])
print("2d array: ",array_2d)

2d array:  [[1 2 3]
 [4 5 6]]


# list vs numpy array



In [ ]:
np_array=np.array([1,2,3]) #elment type multiplication
print("pythn array multiplication: ",np_array*2)

pythn array multiplication:  [2 4 6]


In [12]:
np_array=np.arange(1000)*2

creating array from scartch


In [14]:
#zeroes
zeroes=np.zeros((3,4))
print(zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
ones=np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
fulls=np.full((2,2),7)
print(fulls)

[[7 7]
 [7 7]]


In [18]:
random=np.random.random((2,3))
print(random)

[[0.6461714  0.78857966 0.60788704]
 [0.4487998  0.33320604 0.7755347 ]]


In [23]:
sequence=np.arange(10,10,2)
print(sequence)

[]


## Vector , Matrix,tensor

In [24]:
vector=np.array([1,2,3])
print(vector)

[1 2 3]


In [33]:


tensor = np.array([ [[1,2],[3,4]],
                    [[5,6],[7,8]] ])

print(tensor)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties

In [37]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape: ",arr.shape)
print("dimension: ",arr.ndim)
print("size: ",arr.size)
print("type: ",arr.dtype)

shape:  (2, 3)
dimension:  2
size:  6
type:  int64


# Array reshaping

In [51]:
arr=np.array([1,2,3,4,5,6])
print(arr )

reshaped=arr.reshape((2,3))
print(reshaped)

flatened=reshaped.flatten()
print(flatened)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## Transposed

In [54]:
print(reshaped)
transpose=reshaped.T
print(transpose)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
